"""initial

Revision ID: 1c33a815f107
Revises: 
Create Date: 2026-04-20 22:35:24.862543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c33a815f107'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.create_index('idx_options_name', ['name'], unique=True)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('source_directory', sa.Text(), nullable=False),
    sa.Column('anime_provider', sa.Text(), nullable=False),
    sa.Column('anime_external_id', sa.Text(), nullable=False),
    sa.Column('speaker_mapping_status', sa.Text(), server_default='awaiting_discovery', nullable=False),
    sa.Column('status', sa.Text(), server_default='new', nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('idx_projects_mapping_status', ['speaker_mapping_status'], unique=False)
        batch_op.create_index('idx_projects_status', ['status'], unique=False)

    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='new', nullable=False),
    sa.Column('blocking_reason', sa.Text(), nullable=True),
    sa.Column('detected_subtitle_format', sa.Text(), nullable=True),
    sa.Column('subtitle_track_index', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error_code', sa.Text(), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'relative_path')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index('idx_files_project_blocking_reason', ['project_id', 'blocking_reason'], unique=False)
        batch_op.create_index('idx_files_project_status', ['project_id', 'status'], unique=False)

    op.create_table('project_characters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('social_position', sa.Text(), nullable=True),
    sa.Column('aliases', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_characters', schema=None) as batch_op:
        batch_op.create_index('idx_project_characters_project', ['project_id'], unique=False)

    op.create_table('project_speakers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='queued', nullable=False),
    sa.Column('dedupe_key', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), server_default='100', nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('idx_jobs_file_status', ['file_id', 'status'], unique=False)
        batch_op.create_index('idx_jobs_project_status', ['project_id', 'status'], unique=False)
        batch_op.create_index('idx_jobs_status_priority_scheduled', ['status', 'priority', 'scheduled_at'], unique=False)

    op.create_table('speaker_character_mappings',
    sa.Column('project_speaker_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['project_characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_speaker_id'], ['project_speakers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_speaker_id', 'character_id')
    )
    with op.batch_alter_table('speaker_character_mappings', schema=None) as batch_op:
        batch_op.create_index('idx_speaker_character_mappings_character', ['character_id'], unique=False)

    op.create_table('subtitle_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('line_index', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('layer', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('style', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('margin_l', sa.Integer(), nullable=True),
    sa.Column('margin_r', sa.Integer(), nullable=True),
    sa.Column('margin_v', sa.Integer(), nullable=True),
    sa.Column('effect', sa.Text(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.Column('translation_status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('is_user_edited', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_locked', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_approved', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'line_index')
    )
    with op.batch_alter_table('subtitle_events', schema=None) as batch_op:
        batch_op.create_index('idx_subtitle_events_file_event_type', ['file_id', 'event_type'], unique=False)
        batch_op.create_index('idx_subtitle_events_file_name', ['file_id', 'name'], unique=False)
        batch_op.create_index('idx_subtitle_events_file_translation_status', ['file_id', 'translation_status'], unique=False)

    op.create_table('subtitle_styles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('style_name', sa.Text(), nullable=False),
    sa.Column('font_name', sa.Text(), nullable=False),
    sa.Column('font_size', sa.Float(), nullable=False),
    sa.Column('primary_colour', sa.Text(), nullable=True),
    sa.Column('secondary_colour', sa.Text(), nullable=True),
    sa.Column('outline_colour', sa.Text(), nullable=True),
    sa.Column('back_colour', sa.Text(), nullable=True),
    sa.Column('bold', sa.Integer(), nullable=True),
    sa.Column('italic', sa.Integer(), nullable=True),
    sa.Column('underline', sa.Integer(), nullable=True),
    sa.Column('strikeout', sa.Integer(), nullable=True),
    sa.Column('scale_x', sa.Float(), nullable=True),
    sa.Column('scale_y', sa.Float(), nullable=True),
    sa.Column('spacing', sa.Float(), nullable=True),
    sa.Column('angle', sa.Float(), nullable=True),
    sa.Column('border_style', sa.Integer(), nullable=True),
    sa.Column('outline', sa.Float(), nullable=True),
    sa.Column('shadow', sa.Float(), nullable=True),
    sa.Column('alignment', sa.Integer(), nullable=True),
    sa.Column('margin_l', sa.Integer(), nullable=True),
    sa.Column('margin_r', sa.Integer(), nullable=True),
    sa.Column('margin_v', sa.Integer(), nullable=True),
    sa.Column('encoding', sa.Integer(), nullable=True),
    sa.Column('replacement_font_name', sa.Text(), nullable=True),
    sa.Column('replacement_font_size', sa.Float(), nullable=True),
    sa.Column('font_check_status', sa.Text(), server_default='unchecked', nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'style_name')
    )
    with op.batch_alter_table('subtitle_styles', schema=None) as batch_op:
        batch_op.create_index('idx_subtitle_styles_file_font_check_status', ['file_id', 'font_check_status'], unique=False)

    op.create_table('subtitles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('script_type', sa.Text(), nullable=True),
    sa.Column('wrap_style', sa.Integer(), nullable=True),
    sa.Column('play_res_x', sa.Integer(), nullable=True),
    sa.Column('play_res_y', sa.Integer(), nullable=True),
    sa.Column('scaled_border_and_shadow', sa.Text(), nullable=True),
    sa.Column('layout_res_x', sa.Integer(), nullable=True),
    sa.Column('layout_res_y', sa.Integer(), nullable=True),
    sa.Column('ycbcr_matrix', sa.Text(), nullable=True),
    sa.Column('kerning', sa.Text(), nullable=True),
    sa.Column('extra_script_info_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    with op.batch_alter_table('subtitles', schema=None) as batch_op:
        batch_op.create_index('idx_subtitles_file', ['file_id'], unique=False)

    op.create_table('qa_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('subtitle_event_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('qa_type', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('is_resolved', sa.Integer(), server_default='0', nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subtitle_event_id'], ['subtitle_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qa_items', schema=None) as batch_op:
        batch_op.create_index('idx_qa_items_event', ['subtitle_event_id'], unique=False)
        batch_op.create_index('idx_qa_items_file_resolved_severity', ['file_id', 'is_resolved', 'severity'], unique=False)

    op.create_table('subtitle_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('translate_from_line', sa.Integer(), nullable=False),
    sa.Column('translate_to_line', sa.Integer(), nullable=False),
    sa.Column('context_prepend_from_line', sa.Integer(), nullable=True),
    sa.Column('context_prepend_to_line', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('llm_review_needed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'chunk_index')
    )
    with op.batch_alter_table('subtitle_chunks', schema=None) as batch_op:
        batch_op.create_index('idx_subtitle_chunks_file', ['file_id'], unique=False)
        batch_op.create_index('idx_subtitle_chunks_file_status', ['file_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qa_items', schema=None) as batch_op:
        batch_op.drop_index('idx_qa_items_file_resolved_severity')
        batch_op.drop_index('idx_qa_items_event')

    op.drop_table('qa_items')
    with op.batch_alter_table('subtitle_chunks', schema=None) as batch_op:
        batch_op.drop_index('idx_subtitle_chunks_file_status')
        batch_op.drop_index('idx_subtitle_chunks_file')

    op.drop_table('subtitle_chunks')
    with op.batch_alter_table('subtitles', schema=None) as batch_op:
        batch_op.drop_index('idx_subtitles_file')

    op.drop_table('subtitles')
    with op.batch_alter_table('subtitle_styles', schema=None) as batch_op:
        batch_op.drop_index('idx_subtitle_styles_file_font_check_status')

    op.drop_table('subtitle_styles')
    with op.batch_alter_table('subtitle_events', schema=None) as batch_op:
        batch_op.drop_index('idx_subtitle_events_file_translation_status')
        batch_op.drop_index('idx_subtitle_events_file_name')
        batch_op.drop_index('idx_subtitle_events_file_event_type')

    op.drop_table('subtitle_events')
    with op.batch_alter_table('speaker_character_mappings', schema=None) as batch_op:
        batch_op.drop_index('idx_speaker_character_mappings_character')

    op.drop_table('speaker_character_mappings')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('idx_jobs_status_priority_scheduled')
        batch_op.drop_index('idx_jobs_project_status')
        batch_op.drop_index('idx_jobs_file_status')

    op.drop_table('jobs')
    op.drop_table('project_speakers')
    with op.batch_alter_table('project_characters', schema=None) as batch_op:
        batch_op.drop_index('idx_project_characters_project')

    op.drop_table('project_characters')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index('idx_files_project_status')
        batch_op.drop_index('idx_files_project_blocking_reason')

    op.drop_table('files')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('idx_projects_status')
        batch_op.drop_index('idx_projects_mapping_status')

    op.drop_table('projects')
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.drop_index('idx_options_name')

    op.drop_table('options')
    # ### end Alembic commands ###
